#!/bin/bash
# Создать 50 папок, в каждой 100 подпапок, в каждой подпапке по 200 файлов
echo "программа делает не 50, 100 папок и 200 файлов, а 10, 21 папку и 31 файл для экономии времени"
mkdir 50dir
cd 50dir
for((i=1;i<10;i++))
do
mkdir $i
cd $i

for((j=1;j<21;j++))
do
mkdir $j
cd $j

for((k=1;k<31;k++))
do
touch $k
done
cd ..

done
cd ..

done



























